# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: "3.9"

    steps:
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: coverage run -m pytest
    - name: Tests report
      run: coverage report
    - name: Run linter
      run: flake8
